# testbench
test_conv.v

# netlist generated by Design Compiler
../conv_syn/netlist/conv_top_syn.v

# Logic Gate models
-v /usr/cadtool/cad/synopsys/SAED32_EDK/lib/stdcell_hvt/verilog/saed32nm_hvt.v

sram_model/sram_256x32b.v
sram_model/sram_20000x100b.v

+define+GATESIM
+access+r