# testbench
test_fc.v

# netlist generated by Design Compiler
../syn/netlist/fc_top_syn.v

# Logic Gate models
-v /usr/cadtool/cad/synopsys/SAED32_EDK/lib/stdcell_hvt/verilog/saed32nm_hvt.v

sram_model/sram_256x32b.v
sram_model/sram_20250x80b.v

+define+GATESIM
+access+r
